version: "3.9"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpass123
    networks:
      - shared-network

  backend:
    container_name: project_api
    restart: unless-stopped
    image: node_api:20
    env_file:
      - .env
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
    build:
      context: backend
      target: production
      dockerfile: Dockerfile
      args:
        - name=value
    ports:
      - 3000:3000
    command: ["pnpm", "start"]
    networks:
      - shared-network
    depends_on:
      - mongodb

  frontend:
    container_name: project_frontend
    restart: unless-stopped
    image: vite_react:1.0.0
    build:
      context: frontend
      target: production
      dockerfile: Dockerfile
      args:
        - VITE_API_HOST=${VITE_API_HOST}
    ports:
      - 5173:5173
    command: ["pnpm", "start"]
    networks:
      - shared-network
    depends_on:
      - backend

networks:
  shared-network:
