FROM node:20

RUN pnpm i -g nodemon
RUN mkdir -p /home/app

WORKDIR /home/app

ENV NODE_ENV=development
ENV PORT=${PORT}
ENV CONNECTION_STRING=${CONNECTION_STRING}

COPY . /home/app

EXPOSE ${PORT}

CMD [ "pnpm", "dev" ]